Bugfix/43/scroll to top s2s logo
Project-Based-10-24-vk/Client pull request #107
Opened 2024-10-11 13:57 UTC by lublubczyk

did scrolling to the top of the home page

2024-10-11 17:15 UTC, zim89 approved these changes

2024-10-11 18:44 UTC, lsofiabo approved these changes

2024-10-12 12:06 UTC, VoitV approved these changes

2024-10-12 12:25 UTC, AntonRomanov999 approved these changes

2024-10-14 06:22 UTC, vlad-khrychov requested changes

2024-10-14 06:22 UTC, vlad-khrychov commented on src/containers/layout/navbar/NavBar.tsx
> +
In React we try do not use `getElementById`. Look at `findOffersMenu` (59th row) items have scroll behavior.

2024-10-15 00:56 UTC, nadraharr approved these changes

2024-10-15 08:03 UTC, zim89 approved these changes

2024-10-15 12:14 UTC, lsofiabo approved these changes

2024-10-18 10:53 UTC, vlad-khrychov approved these changes

2024-10-18 13:31 UTC, merged