added popup LoginModel when clicked become a tutor or student buttons
Project-Based-10-24-vk/Client pull request #110
Opened 2024-10-12 06:26 UTC by poggy33

Added popup LoginModel when clicked become a tutor or student buttons insteated SignupModel.

2024-10-12 09:30 UTC, zim89 commented
if the task asks to add a registration dialog, then why add a login dialog? what's the point?

2024-10-12 12:04 UTC, poggy33 commented
> if the task asks to add a registration dialog, then why add a login dialog? what's the point?

50/50

2024-10-12 15:08 UTC, natamrshn requested changes
Please, fix conflicts on your branch!

And due to task description you should add sign up modal, not log-in

2024-10-18 06:55 UTC, lublubczyk approved these changes

2024-10-18 07:28 UTC, nadraharr approved these changes

2024-10-21 15:39 UTC, closed without merging