#57 test for slider-with-input
Project-Based-10-24-vk/Client pull request #113
Opened 2024-10-12 15:51 UTC by natamrshn

add tests to slider with input component:

it should renders correctly

it should call onChange when slider is moved

it should update inputValue correctly when input value is empty

it should update prices when input is blurred and input is greater than max value

it should not update prices when input is blurred and value in input has not changed

2024-10-12 15:53 UTC, zim89 approved these changes

2024-10-13 14:31 UTC, nadraharr approved these changes

2024-10-13 15:02 UTC, VoitV approved these changes

2024-10-14 11:52 UTC, AntonRomanov999 commented on src/tests/unit/components/slider-with-input/SliderWithInput.spec.jsx
> +    expect(defaultProps.onChange).toHaveValue('')
shouldn't it checks value of the input field? onChange is a mock function...

2024-10-15 06:42 UTC, vlad-khrychov requested changes

2024-10-15 06:42 UTC, vlad-khrychov commented on src/tests/unit/components/slider-with-input/SliderWithInput.spec.jsx
> +    defaultValue: 50,
Maybe add a test for this value? The last test can be changed.

2024-10-15 18:23 UTC, lublubczyk approved these changes

2024-10-17 08:14 UTC, vlad-khrychov approved these changes

2024-10-17 10:11 UTC, merged