#105-closePopupConfirm
Project-Based-10-24-vk/Client pull request #119
Opened 2024-10-15 09:17 UTC by nadraharr

Modal window now closes after confirmation.

2024-10-15 09:20 UTC, zim89 approved these changes

2024-10-15 10:00 UTC, natamrshn approved these changes

2024-10-15 11:06 UTC, melyasanya approved these changes

2024-10-15 12:11 UTC, lsofiabo approved these changes

2024-10-15 18:25 UTC, lublubczyk approved these changes

2024-10-15 20:14 UTC, vlad-khrychov requested changes

2024-10-15 20:14 UTC, vlad-khrychov commented on src/components/popup-dialog/PopupDialog.tsx
> +        }
```suggestion
        if (confirmed) {
          closeModal()
        }
```

2024-10-15 20:14 UTC, vlad-khrychov commented on src/components/popup-dialog/PopupDialog.tsx
> +        'Are you sertain you want to close? Any unsaved changes will be lost',
Should we use translation for this message?

2024-10-15 21:58 UTC, nadraharr commented
@vlad-khrychov you're right. The requested changes have been made.

2024-10-18 06:12 UTC, vlad-khrychov approved these changes

2024-10-18 06:43 UTC, merged