Test/54/question editor component
Project-Based-10-24-vk/Client pull request #130
Opened 2024-10-17 09:34 UTC by poggy33

(SP: 1)[#54] Tests for Question Editor Component

2024-10-17 11:23 UTC, nadraharr commented
You need to resolve the conflicts:
~ git checkout develop
~ git pull
~ git checkout <your branch>
~ git merge develop
Then you can deside which version to save in a code editor. Then push again.

2024-10-17 11:28 UTC, nadraharr approved these changes
Please, link your issues to this pull request.

2024-10-18 06:50 UTC, lublubczyk approved these changes

2024-10-20 16:22 UTC, natamrshn requested changes
please, resolve conflicts on branch

2024-10-21 15:49 UTC, poggy33 commented
> please, resolve conflicts on branch

I've resolved conflicts. Please, check.

2024-10-22 11:55 UTC, zim89 approved these changes

2024-10-23 16:37 UTC, vlad-khrychov approved these changes

2024-10-23 16:37 UTC, vlad-khrychov commented on src/tests/unit/components/question-editor/QuestionEditor.spec.jsx
> +    fireEvent.change(answerInput, { target: { value: 'Updated Answer' } })
Try using `userEvent` instead.

2024-10-23 16:37 UTC, vlad-khrychov commented on src/tests/unit/components/question-editor/QuestionEditor.spec.jsx
> +        loading={false}
Maybe it's a good idea to add tests for these props as well.

2024-10-28 08:41 UTC, merged