add general info step validation
Project-Based-10-24-vk/Client pull request #152
Opened 2024-10-24 18:48 UTC by VoitV

2024-10-25 12:31 UTC, nadraharr approved these changes

2024-10-25 13:04 UTC, vlad-khrychov requested changes
Look at the errors from the linter

2024-10-25 13:04 UTC, vlad-khrychov commented on src/components/step-wrapper/StepWrapper.jsx
> +  const handleSetStep = useCallback(
Add dependencies or delete `useCallback`

2024-10-25 13:04 UTC, vlad-khrychov commented on src/containers/tutor-home-page/general-info-step/GeneralInfoStep.jsx
> +  }, [data])
```suggestion
  }, [data, setIsValidated])
```

2024-10-30 13:05 UTC, poggy33 approved these changes

2024-11-01 10:08 UTC, merged