subjects fetching
Project-Based-10-24-vk/Client pull request #178
Opened 2024-10-29 14:21 UTC by nadraharr

Client part here.
Backend part:

2024-10-30 13:03 UTC, poggy33 approved these changes

2024-10-30 13:21 UTC, VoitV approved these changes

2024-10-30 15:24 UTC, vlad-khrychov requested changes
Fix 74-76 rows

2024-10-31 14:16 UTC, zim89 approved these changes

2024-10-31 15:56 UTC, vlad-khrychov approved these changes

2024-11-01 13:40 UTC, merged